import { atom, map, type WritableAtom, type MapStore } from 'nanostores';
import type { editor } from 'monaco-editor'; // For editor view state

// Define the structure of the editor state for a session
export interface SessionEditorFileState { // Mirroring EditorFileState from editor.ts
  filePath: string; // Redundant if key is filePath, but explicit.
  content: string;
  viewState?: editor.ICodeEditorViewState | null;
  isBinary?: boolean;
}

export interface SessionEditorState {
  openFilePaths: string[];
  activeFilePath?: string;
  fileStates: Record<string, SessionEditorFileState>; // filePath maps to its state
}

// Define the structure of a single terminal's state for a session
export interface SessionTerminalInstance {
  id: string; // Unique ID for this terminal instance within the session
  title: string; // e.g., "Terminal 1", "Bolt Terminal"
  // We can't easily save/restore live processes.
  // We can save the visible buffer content.
  bufferContent?: string;
  // We might also save a list of commands if we parse them, but that's more complex.
  // For now, just the buffer.
}

// Define the structure of the terminal state for a session
export interface SessionTerminalState {
  terminals: SessionTerminalInstance[];
  activeTerminalId?: string; // ID of the active terminal tab within the session's terminal panel
}

// Define the structure of a single session
export interface AppSession {
  id: string;
  name: string;
  chatId: string;
  editorState: SessionEditorState;
  terminalState: SessionTerminalState;
  chatInput?: string; // Added for saving chat input
  // Potentially add search/browser state here later
  lastAccessed: number;
}

const LOCAL_STORAGE_KEY = 'appSessions';

// Store for the list of all sessions
export const sessionsStore: WritableAtom<AppSession[]> = atom([]);
// Store for the ID of the currently active session
export const activeSessionIdStore: WritableAtom<string | null> = atom(null);

// --- Helper Functions ---

function generateSessionId(): string {
  return `session_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
}

function getChatIdForNewSession(): string {
  // This needs to align with how new chat IDs are generated by useChatHistory.
  // For now, let's assume a similar pattern or a placeholder.
  // Ideally, useChatHistory would provide a way to create/get a new ID.
  return `chat_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
}

// --- Core Session Management ---

export function loadSessionsFromLocalStorage(): void {
  if (typeof localStorage === 'undefined') return;
  try {
    const storedSessions = localStorage.getItem(LOCAL_STORAGE_KEY);
    if (storedSessions) {
      const parsedSessions: AppSession[] = JSON.parse(storedSessions);
      sessionsStore.set(parsedSessions);
      // Set the last accessed session as active, or the first one if none.
      if (parsedSessions.length > 0) {
        const sortedByLastAccessed = [...parsedSessions].sort((a, b) => b.lastAccessed - a.lastAccessed);
        activeSessionIdStore.set(sortedByLastAccessed[0].id);
      } else {
        // If no sessions, create an initial default one
        createNewSession(true); // true to make it active
      }
    } else {
      // No sessions stored, create an initial default one
      createNewSession(true);
    }
  } catch (error) {
    console.error("Failed to load sessions from LocalStorage:", error);
    // Fallback to a new session if loading fails
    sessionsStore.set([]); // Clear potentially corrupted data
    activeSessionIdStore.set(null);
    createNewSession(true);
  }
}

export function saveSessionsToLocalStorage(): void {
  if (typeof localStorage === 'undefined') return;
  try {
    const sessions = sessionsStore.get();
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(sessions));
  } catch (error) {
    console.error("Failed to save sessions to LocalStorage:", error);
    // Optionally, notify the user or try a fallback if critical
  }
}

export function createNewSession(makeActive: boolean = false, name?: string): AppSession {
  const newSessionId = generateSessionId();
  const newChatId = getChatIdForNewSession(); // Each session gets its own chat
  const sessionName = name || `Session ${sessionsStore.get().length + 1}`;

  const newSession: AppSession = {
    id: newSessionId,
    name: sessionName,
    chatId: newChatId,
    editorState: { // Initialize with the new structure
      openFilePaths: [],
      activeFilePath: undefined,
      fileStates: {}, // Empty map initially
    },
    terminalState: {
      terminals: [
        { id: 'bolt_terminal_0', title: 'Bolt Terminal', bufferContent: '' }
      ],
      activeTerminalId: 'bolt_terminal_0',
    },
    chatInput: '', // Initialize chatInput
    lastAccessed: Date.now(),
  };

  const updatedSessions = [...sessionsStore.get(), newSession];
  sessionsStore.set(updatedSessions);

  if (makeActive) {
    setActiveSession(newSessionId);
  }
  saveSessionsToLocalStorage(); // Save immediately
  return newSession;
}

export function setActiveSession(sessionId: string | null): void {
  if (!sessionId) {
    activeSessionIdStore.set(null);
    return;
  }
  const sessions = sessionsStore.get();
  const sessionToActivate = sessions.find(s => s.id === sessionId);

  if (sessionToActivate) {
    // Update lastAccessed timestamp for the newly active session
    const updatedSessions = sessions.map(s =>
      s.id === sessionId ? { ...s, lastAccessed: Date.now() } : s
    );
    sessionsStore.set(updatedSessions); // Update store before saving
    activeSessionIdStore.set(sessionId);
    saveSessionsToLocalStorage(); // Save changes including the new lastAccessed time
  } else {
    console.warn(`Session with ID ${sessionId} not found. Cannot activate.`);
    // If current active session is invalid, try to set to the most recent valid one or null
    if (sessions.length > 0) {
        const sortedByLastAccessed = [...sessions].sort((a, b) => b.lastAccessed - a.lastAccessed);
        activeSessionIdStore.set(sortedByLastAccessed[0].id);
    } else {
        activeSessionIdStore.set(null);
    }
  }
}

export function updateSession(sessionId: string, updates: Partial<Omit<AppSession, 'id' | 'chatId'>>): void {
  const currentSessions = sessionsStore.get();
  const sessionIndex = currentSessions.findIndex(s => s.id === sessionId);

  if (sessionIndex !== -1) {
    const updatedSession = {
      ...currentSessions[sessionIndex],
      ...updates,
      lastAccessed: Date.now(), // Always update lastAccessed on any modification
    };
    const newSessions = [...currentSessions];
    newSessions[sessionIndex] = updatedSession;
    sessionsStore.set(newSessions);
    saveSessionsToLocalStorage();
  } else {
    console.warn(`Session with ID ${sessionId} not found. Cannot update.`);
  }
}

export function closeSession(sessionId: string): void {
  let sessions = sessionsStore.get();
  const sessionToCloseIndex = sessions.findIndex(s => s.id === sessionId);

  if (sessionToCloseIndex === -1) {
    console.warn(`Session with ID ${sessionId} not found. Cannot close.`);
    return;
  }

  sessions = sessions.filter(s => s.id !== sessionId);
  sessionsStore.set(sessions);

  const currentActiveId = activeSessionIdStore.get();
  if (currentActiveId === sessionId) {
    if (sessions.length > 0) {
      // Activate the most recently accessed session among the remaining ones
      const sortedByLastAccessed = [...sessions].sort((a, b) => b.lastAccessed - a.lastAccessed);
      setActiveSession(sortedByLastAccessed[0].id);
    } else {
      // If no sessions left, create a new default one and make it active
      const newDefaultSession = createNewSession(false); // create without making active initially
      setActiveSession(newDefaultSession.id); // then set active
    }
  }
  saveSessionsToLocalStorage();
}

// Initial load when the module is imported (for client-side)
if (typeof window !== 'undefined') {
  loadSessionsFromLocalStorage();
}
